---
extends:
  - eslint:recommended
  - plugin:json/recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 6
env:
  browser: true
  node: true
plugins:
  - "@typescript-eslint"
overrides:
  - parser: "@typescript-eslint/parser"
    files:
      - "*.ts"
