from _pytest.fixtures import FixtureFunctionMarker

from _dependencies.injector import Injector

def register(injector: Injector) -> FixtureFunctionMarker: ...
def require(fixturename: str) -> Requirement: ...

class Requirement: ...
