from typing import Any
from typing import List
from typing import NoReturn
from typing import Tuple

class Package:
    def __init__(self, name: str) -> None: ...
    def __getattr__(self, attrname: str) -> Package: ...

def _make_package_spec(
    dependency: Package,
) -> Tuple[str, _ImportSpec, List[Any], int]: ...

class _ImportSpec:
    def __init__(self, dependency: Package) -> None: ...
    def __call__(self) -> NoReturn: ...
