#!/bin/bash

set -o nounset
set -o pipefail

. venv/bin/activate

git ls-files -z | xargs -0 grep -Z -I -l '' | xargs -0 fix-byte-order-marker
git ls-files -z | xargs -0 grep -Z -I -l '' | xargs -0 end-of-file-fixer
git ls-files -z | xargs -0 grep -Z -I -l '' | xargs -0 mixed-line-ending --fix=lf
git ls-files -z | xargs -0 grep -Z -I -l '' | xargs -0 trailing-whitespace-fixer
file-contents-sorter .gitignore requirements.txt

git ls-files -z '*.py' | xargs -0 pyupgrade --py311-plus

git ls-files -z '*.py' | xargs -0 reorder-python-imports --py311-plus --application-directories=src

git ls-files -z '*.py' | xargs -0 docformatter --wrap-summaries 88 --wrap-descriptions 88 --blank --in-place

git ls-files -z '*.py' | xargs -0 eradicate --aggressive --in-place

git ls-files -z '*.py' | xargs -0 black --target-version=py311 --quiet

git ls-files -z '*.js' '*.ts' '*.md' | xargs -0 npx prettier --prose-wrap=always --write

git ls-files -z '*.toml' | xargs -0 toml-sort --all --no-header --in-place
