#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

. venv/bin/activate

coverage run -m pytest

for example in $(git ls-files 'examples/*.py')
do
    echo $example
    diff <(coverage run $example) ${example%.py}.log
done

coverage combine

coverage report --fail-under 100
