---
name: pipeline
"on":
  push:
    branches:
      - release
      - develop
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - run: |
          git checkout develop || true
          git checkout $GITHUB_HEAD_REF
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - run: ./scripts/install
      - run: ./scripts/check
      - run: ./scripts/test
      - run: ./scripts/review
        if: ${{ github.event_name == 'pull_request' }}
        env:
          DANGER_GITHUB_API_TOKEN: Z2hwX3BZbXFOQWJXMkNkT0NwejNGS1BWZjBWZ3hTS01uSjJRSmVQbAo=
      - run: ./scripts/release
        if: ${{ github.ref == 'refs/heads/release' || github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
